const unshuffledCards = [
    { key: 'acorn-1', type: 'acorn', value: 1, icon: 'nutritionix' },
    { key: 'acorn-2', type: 'acorn', value: 2, icon: 'nutritionix' },
    { key: 'acorn-7', type: 'acorn', value: 7, icon: 'nutritionix' },
    { key: 'acorn-8', type: 'acorn', value: 8, icon: 'nutritionix' },
    { key: 'acorn-9', type: 'acorn', value: 9, icon: 'nutritionix' },
    { key: 'acorn-10', type: 'acorn', value: 10, icon: 'nutritionix' },
    { key: 'acorn-skip', type: 'acorn', value: 'skip', icon: 'nutritionix' },
    { key: 'acorn-change', type: 'acorn', value: 'change', icon: 'nutritionix' },
    { key: 'heart-1', type: 'heart', value: 1, icon: 'heart' },
    { key: 'heart-2', type: 'heart', value: 2, icon: 'heart' },
    { key: 'heart-7', type: 'heart', value: 7, icon: 'heart' },
    { key: 'heart-8', type: 'heart', value: 8, icon: 'heart' },
    { key: 'heart-9', type: 'heart', value: 9, icon: 'heart' },
    { key: 'heart-10', type: 'heart', value: 10, icon: 'heart' },
    { key: 'heart-skip', type: 'heart', value: 'skip', icon: 'heart' },
    { key: 'heart-change', type: 'heart', value: 'change', icon: 'heart' },
    { key: 'leaf-1', type: 'leaf', value: 1, icon: 'leaf' },
    { key: 'leaf-2', type: 'leaf', value: 2, icon: 'leaf' },
    { key: 'leaf-7', type: 'leaf', value: 7, icon: 'leaf' },
    { key: 'leaf-8', type: 'leaf', value: 8, icon: 'leaf' },
    { key: 'leaf-9', type: 'leaf', value: 9, icon: 'leaf' },
    { key: 'leaf-10', type: 'leaf', value: 10, icon: 'leaf' },
    { key: 'leaf-skip', type: 'leaf', value: 'skip', icon: 'leaf' },
    { key: 'leaf-change', type: 'leaf', value: 'change', icon: 'leaf' },
    { key: 'ball-1', type: 'ball', value: 1, icon: 'bowling ball' },
    { key: 'ball-2', type: 'ball', value: 2, icon: 'bowling ball' },
    { key: 'ball-7', type: 'ball', value: 7, icon: 'bowling ball' },
    { key: 'ball-8', type: 'ball', value: 8, icon: 'bowling ball' },
    { key: 'ball-9', type: 'ball', value: 9, icon: 'bowling ball' },
    { key: 'ball-10', type: 'ball', value: 10, icon: 'bowling ball' },
    { key: 'ball-skip', type: 'ball', value: 'skip', icon: 'bowling ball' },
    { key: 'ball-change', type: 'ball', value: 'change', icon: 'bowling ball' }
];

export { unshuffledCards };